import React from 'react';
import { ChatMessage, Theme } from '../types';
import { THEME_CONFIGS, CUSTOM_THEME_CONFIG } from '../constants';
import SpinnerIcon from './icons/SpinnerIcon';
import MarkdownRenderer from './MarkdownRenderer';
import StreamingText from './StreamingText';
import { useLanguage } from '../contexts/LanguageContext';

interface MessageProps {
  message: ChatMessage;
  theme: Theme;
  isLoading: boolean;
  isLastMessage: boolean;
}

const Message: React.FC<MessageProps> = ({ message, theme, isLoading, isLastMessage }) => {
  const { t } = useLanguage();
  const isUser = message.role === 'user';
  const themeConfig = theme === Theme.Custom
    ? CUSTOM_THEME_CONFIG
    : THEME_CONFIGS[theme as Exclude<Theme, Theme.Custom>];

  const isStreaming = message.role === 'assistant' && isLastMessage && isLoading && message.type === 'text';

  const renderContent = () => {
    switch (message.type) {
      case 'loading':
        return (
          <div className="flex items-center space-x-2">
            <SpinnerIcon className="w-5 h-5" />
            <span>{message.content || t('thinking')}</span>
          </div>
        );
      case 'image':
        return (
          <img
            src={message.content}
            alt="Generated by AI"
            className="rounded-lg max-w-sm"
          />
        );
      case 'error':
        return <p className="text-red-400">{message.content}</p>;
      case 'text':
      default:
        if (isUser) {
          return (
             <div className="flex flex-col gap-2">
                {message.imageUrl && (
                    <img src={message.imageUrl} alt="User upload" className="rounded-lg max-w-xs" />
                )}
                <p className="whitespace-pre-wrap">{message.content}</p>
             </div>
          );
        }
        if (isStreaming) {
          return <StreamingText content={message.content} />;
        }
        return <MarkdownRenderer content={message.content} theme={theme} />;
    }
  };

  return (
    <div className={`flex ${isUser ? 'justify-end' : 'justify-start'}`}>
      <div
        className={`max-w-xl lg:max-w-2xl px-4 py-3 rounded-xl border ${
          isUser
            ? `${themeConfig.userBubble} ${themeConfig.userText} border-transparent`
            : `${themeConfig.assistantBubble} ${themeConfig.assistantText} ${theme === Theme.White ? 'border-gray-200' : 'border-gray-800'}`
        }`}
      >
        {renderContent()}
      </div>
    </div>
  );
};

export default Message;